inveniosoftware/invenio-records-rest

- AUTHORS.rst
- CONTRIBUTING.rst
- README.rst
- RELEASE-NOTES.rst
- docs/conf.py
- invenio_records_rest/ext.py
- invenio_records_rest/version.py
* Standardises human package name from `-Rest` to `-REST` following the
usual practices.
* Amends "overhanging" ReStructuredText headlines.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> global: Invenio-Records-REST capitalisation

- .editorconfig
- .gitignore
- examples/app.py
- invenio_records_rest/ext.py
- invenio_records_rest/serializers.py
- invenio_records_rest/version.py
- invenio_records_rest/views.py
- setup.py
- tests/conftest.py
- tests/permissions.py
- tests/test_invenio_records_rest.py
* NEW Adds customizable access control to record views. Allow
configuring different permissions per endpoint. (reference #14)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> views: access control

- invenio_records_rest/config.py
- invenio_records_rest/ext.py
- invenio_records_rest/serializers.py
- invenio_records_rest/views.py
- tests/access_records.py
- tests/conftest.py
- tests/test_invenio_records_rest.py
* Fixes problem with undefined permission factory configuration
variables.
* Forces search index to be specified in RECORDS_REST_ENDPOINTS.
(closes #21)
* Fixes bug which did not allow for an empty document type.
* Fixes problem with _created/_updated being required in record source.
> global: usage fixes

- invenio_records_rest/query.py
- invenio_records_rest/views.py
- tests/test_query.py
* Add support for customizing query generation and thereby support
multiple query parsers.
* Adds query factory for Elasticsearch Lucene syntax.
> views: query factory support

- invenio_records_rest/links.py
- invenio_records_rest/views.py
* Uses relative endpoints for generating URLs.
> global: relative endpoints

- invenio_records_rest/config.py
- invenio_records_rest/utils.py
- invenio_records_rest/views.py
- tests/conftest.py
- tests/test_ext.py
@lnielsen can you please review it? We can now use `pid, record = request.view_args['pid_value']` anywhere.
I would like to also remove `@pass_record` decorator.
--
> global: PID resolver as URL converter

- invenio_records_rest/views.py
* NOTE It is necessary to add models retrieved as view arguments to
current database session since new SQLAlchemy scoped session is
created when request context is pushed.
> global: addition of models from view args

- invenio_records_rest/serializers/response.py
- tests/test_views_search.py
* FIX Fixes missing links between URIs in response headers. These
links were included in the JSON object, but not in the HTTP headers,
as suggested on https://tools.ietf.org/html/rfc5988.  (closes #70)
* Increases test coverage.
> views: addition of links in response headers

- .tx/config
- babel.ini
- docs/conf.py
- invenio_records_rest/translations/en/LC_MESSAGES/messages.po
- invenio_records_rest/views.py
- setup.cfg
- setup.py
- tests/test_views_search.py
* Adds a handler that process the errors coming from ElasticSearch in
case of a bad request. (closes #84)
* Fixes issue with `Sphinx 1.4`.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> views: addition of elasticsearch error handler

- RELEASE-NOTES.rst
- invenio_records_rest/translations/en/LC_MESSAGES/messages.po
- setup.cfg
- setup.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> global: inveniosoftware.org

- examples/app.py
- run-tests.sh
* Fixes the example application using the correct PID converter.
* Adds the shebang to run-tests.sh script.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> examples: fixture of PIDConverter

- invenio_records_rest/views.py
* Moves creation of errors handlers into separate function which can
be used by e.g. Invenio-Deposit to install the same error handlers.
> views: error handlers move

- invenio_records_rest/config.py
- invenio_records_rest/ext.py
- invenio_records_rest/links.py
- invenio_records_rest/utils.py
- invenio_records_rest/views.py
- tests/conftest.py
- tests/test_utils.py
* NEW Introduces new RECORDS_REST_PID_TYPE_DEFAULT_ENDPOINT config
variable, needed in order to know which default endpoint corresponds
to which pid_type when building URIs. (closes #101)
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
(supersedes #109)
> utils: new get_default_endpoint_for()

- AUTHORS.rst
- invenio_records_rest/serializers/datacite.py
- setup.py
- tests/test_serializer_datacite.py
Added wrapper class for the new Datacite v4.0 support in Datacite module (see https://github.com/inveniosoftware/datacite/pull/18)
INCOMPATIBLE: the constructor of `OAIDataCiteSerializer` now takes a "serializer" parameter instead of a "v31".
Signed-off-by: Rémi Ducceschi <remi.ducceschi@gmail.com>
> global: Datacite v4.0 support.

- invenio_records_rest/serializers/citeproc.py
* Escapes apostrophe character in the final result returned.
Signed-off-by: satwikkansal <satwikkansal@gmail.com>
FIxes https://github.com/zenodo/zenodo/issues/959
> serializers: citeproc serializer

- tests/test_custom_endpoints.py
*Adds tests checking that invenio-records-rest
can be used as a library. (closes #130 )
Signed-off-by: PaulinaLach paulina.malgorzata.lach@cern.ch
> Test endpoints

- docs/conf.py
- invenio_records_rest/config.py
- invenio_records_rest/errors.py
- invenio_records_rest/utils.py
- invenio_records_rest/views.py
- tests/test_error_handlers.py
* Introduces the 'error_handlers' key for the 'RECORDS_REST_ENDPOINTS'
config variable which allows for registration of custom error
uandlers for exceptions and HTTP status codes occuring in specific
endpoint of the REST API blueprint views. (closes #152)
> views: configurable error handling

- invenio_records_rest/_compat.py
- invenio_records_rest/links.py
- invenio_records_rest/serializers/base.py
- invenio_records_rest/serializers/datacite.py
- invenio_records_rest/serializers/dc.py
- invenio_records_rest/serializers/json.py
- invenio_records_rest/serializers/jsonld.py
- invenio_records_rest/serializers/marshmallow.py
- invenio_records_rest/views.py
- tests/test_links.py
- tests/test_serializer_marshmallow.py
* NEW Adds support for marshmallow context in MarshmallowMixin.
(closes #110)
* BETTER Refactors the serializers in order to make them work
better as mixins.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
> global: refactor serializers

- docs/conf.py
- invenio_records_rest/config.py
- invenio_records_rest/views.py
- setup.py
- tests/conftest.py
- tests/test_views_item_delete.py
- tests/test_views_item_patch.py
- tests/test_views_item_put.py
- tests/test_views_list_post.py
* CHANGE indexing of changes after PUT, DELETE, PATCH, POST
* Extend the tests to check for proper indexing
Closes https://github.com/inveniosoftware/invenio-records-rest/issues/172
Signed-off-by: Dinos Kousidis <konstantinos.kousidis@cern.ch>
Co-authored-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> global: indexing after actions

- invenio_records_rest/views.py
- removed the cast to type `str` for the suggestion request value which
was failing for strings containing non ASCII chars.
> suggestion: removed str cast for request value

- invenio_records_rest/sorter.py
- tests/test_sorter.py
this addresses #189 . I don't know if we want to invest some time on @egabancho suggestion in order to remove `six` from dependency.
> sorter: fix unicode handling

- invenio_records_rest/serializers/json.py
- tests/test_serializer_json.py
* Drops usage of `request.is_xhr` since it's deprecated in
flask/werkzeug. (closes #204)
* Prints pretty JSON in debug mode.
> serializers: drop usage of request.is_xhr for JSON

- CHANGES.rst
- invenio_records_rest/config.py
- invenio_records_rest/ext.py
- invenio_records_rest/version.py
- invenio_records_rest/views.py
Change naming of 'read_list' permissions to 'list' for better consistency
> Refactor: change naming of 'read_list' permissions to 'list' 

- invenio_records_rest/schemas/__init__.py
- invenio_records_rest/schemas/json.py
- tests/test_marshmallow_loader.py
* ADD Nested class which overrides the _validate_missing method,
and reports errors for the topmost missing fields.
Closes #223 
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> schemas: Nested class w/out recursive error check

- CHANGES.rst
- invenio_records_rest/config.py
- invenio_records_rest/version.py
- invenio_records_rest/views.py
- tests/test_views_suggesters.py
Make ES5 suggesters support [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-source-filtering.html) in order to save network overhead by filtering out useless fields from the `_source` key (or just strip `_source` altogether) returned in the response.
Suggester fields configuration should now contain a `_source` key that will specify the source filtering for each suggestion field. The possible values for the `_source` key are the same as the ones specified in source filtering documentation.
Example configuration:
```
'suggesters': {
'author': {
'_source': ['name', 'age'],
'completion': {
'field': 'author_suggest',
},
}
}
```
With the current test structure, it is not possible to add a reliable test to handle both ES2 and ES5.
Signed-off-by: …
> views: suggesters support source filtering for ES5

- invenio_records_rest/errors.py
- invenio_records_rest/views.py
* Adds an exception that inherits from  REST Exception and represents an unhandled exception.
* Logs the exception so it goes to Sentry/Logging.
* Returns a serializable response so the App does not crash (Internal Server Error).
* Users should change ``RECORDS_REST_ELASTICSEARCH_ERROR_HANDLERS`` to adapt the errors to their needs (e.g. return parsing errors, which at the moment are not handled).
Closes https://github.com/inveniosoftware/invenio-indexer/issues/88
Outdates https://github.com/inveniosoftware/troubleshooting/issues/24
> error handling: return serializable unhandled error

- invenio_records_rest/loaders/__init__.py
- invenio_records_rest/schemas/__init__.py
- invenio_records_rest/schemas/fields/__init__.py
- invenio_records_rest/schemas/fields/generated.py
- invenio_records_rest/schemas/fields/marshmallow_contrib.py
- invenio_records_rest/schemas/fields/persistentidentifier.py
- invenio_records_rest/schemas/json.py
- invenio_records_rest/serializers/json.py
- tests/data/testrecords.json
- tests/test_custom_fields.py
- tests/test_marshmallow_loader.py
Fixes: https://github.com/inveniosoftware/invenio-records-rest/issues/232
Fixes: [cookiecutter-invenio-instance#97](https://github.com/inveniosoftware/cookiecutter-invenio-instance#97)
In order to use it the loader should be overwritten with:
```python
record_loaders={
'application/json': ('invenio_records_rest.loaders:json_pid_checker')
},
```
And add the PID attribute name on the environment / config file:
```python
[ INVENIO_ ]RECORDS_REST_PID_ATTR_NAME = 'control_number'
```
For the code:
- Should the "get_pid" function be customizable (e.g. through ``import_string()``)? If not, is ``json.py`` the best place to be for this function, ``utils.py``?
- There is a test file for [custom marshmallow loaders](https://github.com/inveniosoftware/invenio-records-rest/blob/master/tests/test_marshm …
> Marshmallow schema and field updates for PID and other helpers

- CHANGES.rst
- invenio_records_rest/config.py
- invenio_records_rest/loaders/__init__.py
- invenio_records_rest/schemas/__init__.py
- invenio_records_rest/serializers/__init__.py
- invenio_records_rest/version.py
- invenio_records_rest/views.py
- setup.py
- tests/conftest.py
- tests/test_views_search.py
* Adds ``RECORDS_REST_DEFAULT_SEARCH_RESULTS_SIZE``
variable to change the default ``size`` of the search results.
The default value remains ``10``.
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> config: addition of configurable search results size

- invenio_records_rest/schemas/json.py
Adds a getter method to inject pid field in order to be able to inject different pids from different
record classes
> loaders: inject pid field through getter method

- invenio_records_rest/schemas/fields/marshmallow_contrib.py
- tests/test_marshmallow_contrib.py
> marshamllow: use getfullargspec instead getargspec in python3

- invenio_records_rest/__init__.py
- invenio_records_rest/serializers/csv.py
- tests/test_serializer_csv.py
Adding class for serializing records into CSV format.
> CSV serialize

- invenio_records_rest/config.py
- invenio_records_rest/views.py
- tests/conftest.py
- tests/test_views_serializers.py
- allow to choose the response serializer to use via URL arg for search
results as already done for record item.
> global: serializer via url arg for search

- invenio_records_rest/views.py
- tests/test_views_search.py
* Since the `size` url param is internally passed to the ES
query as Python list[start:size], its upper limit value should be
equal to `max_result_window`
> views: fix wrong `size` param upper limit

- invenio_records_rest/loaders/marshmallow.py
- invenio_records_rest/schemas/json.py
- tests/test_marshmallow_loader.py
If there are nested fields and there is an error in one of the nested subfields, the `field` returned in the error is just the name of the leaf field.
What this does is store the parents of a nested field so if you had a nested schema like this:
`document` -> `author` -> `name.Str()` the field returned in the error would just be `name`, losing the information about its parents. This PR would also add `parents=['document', 'author']`
> loaders: add nested parents fields to errors

- .travis.yml
- CHANGES.rst
- invenio_records_rest/version.py
- requirements-devel.txt
- setup.py
* update travis.yml
* drop support for Python 2.7
* closes #289
> global: manage flask dependency centrally

- .travis.yml
- invenio_records_rest/_compat.py
- invenio_records_rest/utils.py
- invenio_records_rest/views.py
- run-tests.sh
* Makes the PIDConverter lazier in terms of initializing its "resolver"
class member, which allows e.g. passing a "record_class" that might
depend on application context being loaded.
> utils: make PID converter lazier

- invenio_records_rest/loaders/marshmallow.py
Changed the params of the get_body function to accommodate for the "scope" positional argument needed in newer releases of werkzeug
> Marshmallow Errors: flask 2 compatibility change

- CHANGES.rst
- invenio_records_rest/__init__.py
- invenio_records_rest/facets.py
- invenio_records_rest/views.py
- setup.cfg
- tests/conftest.py
- tests/test_custom_endpoints.py
- tests/test_error_handlers.py
- tests/test_views_search.py
- migrate: flask_babelex replaced by invenio_i18n
- fix: black due new black version
- fix: tests
- NOTE: invenio-i18n, invenio-pidstore, invenio-records have to be released before
> migrate to flask babel

- invenio_records_rest/facets.py
New filter for fields used in nested facets. Example:
* Imagine a filter by type of file (Documentation, Dataset, Environment, ...) and the types could have subtypes (Documentation has About, Guide, Help, ...)
* This filter will give things like: 
* all Documentation or Dataset
* Documentation::About or Dataset
* Documentation::About or Dataset::Simulated
Note that there are issues if the name of the subtype appears in multiple categories.
> facets: Create a new filter for nested filters

- invenio_records_rest/config.py
- invenio_records_rest/views.py
Addresses https://github.com/inveniosoftware/invenio-records-rest/issues/328
> search: possibility to specify a different query_parser

- CHANGES.rst
- invenio_records_rest/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
> release: v2.4.0

- invenio_records_rest/loaders/marshmallow.py
- invenio_records_rest/schemas/fields/generated.py
- invenio_records_rest/schemas/json.py
- invenio_records_rest/utils.py
- tests/test_custom_fields.py
- tests/test_marshmallow_loader.py
Remove deprecation warnings from marshmallow, like:
```
/opt/invenio/var/instance/python/lib/python3.9/site-packages/invenio_records_rest/schemas/json.py:14: DeprecationWarning: The '__version_info__' attribute is deprecated and will be removed in in a future version. Use feature detection or 'packaging.Version(importlib.metadata.version("marshmallow")).release' instead.
from marshmallow import __version_info__ as marshmallow_version
/opt/invenio/var/instance/python/lib/python3.9/site-packages/invenio_records_rest/schemas/fields/generated.py:13: DeprecationWarning: The '__version_info__' attribute is deprecated and will be removed in in a future version. Use feature detection or 'packaging.Version(importlib.metadata.version("marshmallow")).release' …
```
> marshmallow: remove deprecation warning

- invenio_records_rest/config.py
- invenio_records_rest/errors.py
- invenio_records_rest/views.py
- run-tests.sh
Fix: some strings that could appear inside UI were not marked with `gettext/lazy_gettext`.
This PR adds `lazy_gettext` into places where the string is read when invenio is started (static initialization) and `gettext` elsewhere
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder** …
> i18n: Fix untranslated strings in facets

- .gitignore
- invenio_records_rest/translations/messages.pot
> i18n: remove .pot files from .gitignore

- invenio_records_rest/utils.py
* UserWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html. The
pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
> fix: pkg_resources DeprecationWarning
