AUTHORS.rst
CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py
requirements-devel.txt
setup.py
tests/test_invenio_records_rest.py

Invenio-Records-REST v1.0.0a1

---

setup.py

* Adds entry point so that extension can be discovered by
Invenio-Base.

installation: entry point addition

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py
requirements-devel.txt

(closes #15)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

release: v1.0.0a3

---

invenio_records_rest/version.py

version: post-release bump

---

.travis.yml
examples/app.py
invenio_records_rest/ext.py
invenio_records_rest/serializers.py
invenio_records_rest/views.py
requirements-devel.txt
setup.py
tests/access_records.py
tests/conftest.py
tests/test_invenio_records_rest.py

global: search integration

---

.travis.yml
invenio_records_rest/errors.py
invenio_records_rest/views.py
tests/test_search.py

* Adds proper handling of invalid query syntax errors.

views: query syntax error handling

---

.travis.yml
invenio_records_rest/config.py
invenio_records_rest/errors.py
invenio_records_rest/ext.py
invenio_records_rest/sorter.py
invenio_records_rest/views.py
tests/conftest.py
tests/test_ext.py
tests/test_search.py
tests/test_sorter.py
tests/test_views_options.py

* (addresses inveniosoftware/invenio-search#52)
* (addresses inveniosoftware/invenio-search#53)

sorter: sorting for REST API

---

invenio_records_rest/views.py

* Adds self link to search results page.

views: search result self link

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

release: v1.0.0a6

---

invenio_records_rest/config.py
setup.py
tests/helpers.py
tests/test_invenio_records_rest.py
tests/test_search.py
tests/test_serializers.py
tests/test_views_options.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

global: fix recid fetcher and minter name

---

invenio_records_rest/sorter.py
tests/test_sorter.py

* Fixes issue with hard-coded field name for geolocation sorting.

sorter: geolocation sort fix

---

invenio_records_rest/serializers/datacite.py
invenio_records_rest/serializers/dc.py
setup.py

* Adds DataCite v3.1 XML serializer.

serializers: datacite xml serialiser

---

invenio_records_rest/serializers/datacite.py
setup.py
tests/test_serializer_datacite.py
tests/test_serializers_dc.py

* Adds tests for DataCite serializer.
* Fixes issue with OAI-PMH serialization.

serializers: datacite tests

---

invenio_records_rest/config.py
invenio_records_rest/ext.py
invenio_records_rest/utils.py
invenio_records_rest/views.py
tests/conftest.py
tests/test_permissions.py

* Adds default permission for all POST, PUT and DELETE methods.

global: deny POST, PUT and DELETE by default

---

invenio_records_rest/serializers/base.py
invenio_records_rest/serializers/marshmallow.py
tests/test_serializer_base.py

serializers: optional jsonref replacement

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a8

---

invenio_records_rest/views.py

views: configurable record class

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a9

---

invenio_records_rest/views.py
tests/conftest.py

Reviewed-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

views: fix record post permissions

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a12

---

invenio_records_rest/utils.py
invenio_records_rest/views.py

* Makes evaluation of URL argument of `pid` type lazy.
--
ups ...

global: lazy PID value evaluation

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

release: v1.0.0a13

---

invenio_records_rest/facets.py
tests/test_facets.py

* NEW Implements a filter that filters a field based on a range of
values. This is used in the year filter facet for invenio-search-ui.
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

facets: new filter for ranges

---

examples/app.py
invenio_records_rest/memento.py
setup.py
tests/conftest.py
tests/test_memento.py

@lnielsen @tiborsimko can you please have a look?

memento: basic support

---

AUTHORS.rst
invenio_records_rest/serializers/citeproc.py
setup.py
tests/test_serializer_citeproc.py

* Adds a citation formatting serializer.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

serializers: citeproc serializer

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a14

---

AUTHORS.rst
invenio_records_rest/errors.py
invenio_records_rest/serializers/citeproc.py
invenio_records_rest/utils.py
invenio_records_rest/views.py
tests/test_serializer_citeproc.py

* Provides better error messages, instead of just using Flask's `abort`.
(closes #32)
Signed-off-by: Orestis Melkonian <melkon.or@gmail.com>

errors: more specific error messages

---

MANIFEST.in
examples/app.py
examples/requirements.txt

In a similar spirit to https://github.com/inveniosoftware/invenio-records-ui/pull/45, here's some documentation updates for the example and the addition of a `requirements.txt`, as suggested in the [informal RFC](https://gitter.im/inveniosoftware/invenio?at=578c2b2d196179690efc8cc9).

examples: addition of requirements.txt

---

.travis.yml
CONTRIBUTING.rst
MANIFEST.in
examples/app-setup.sh
examples/app-teardown.sh
examples/app.py
setup.py
tests/test_examples_app.py

* Adds test_example_app.py. (closes #108)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

tests: addition of test_example_app.py

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a16

---

docs/conf.py

docs: ReadTheDocs in intersphinx config

---

invenio_records_rest/config.py
invenio_records_rest/ext.py
invenio_records_rest/views.py
tests/test_views_search.py

* BETTER Moves Elasticsearch error handling to application config,
allowing for wider coverage of error codes. (closes #122)
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>

search: error handling

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a17

---

examples/app.py
setup.py
tests/conftest.py

Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

installation: Flask>=0.11

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

release: v1.0.0a18

---

invenio_records_rest/serializers/jsonld.py
invenio_records_rest/serializers/marshmallow.py
setup.py
tests/test_serializer_jsonld.py

Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

serialization: JSON-LD serializer

---

invenio_records_rest/errors.py
invenio_records_rest/views.py
setup.cfg
tests/test_views_list_post.py

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

errors: adds jsonschema validation class with error message

---

invenio_records_rest/config.py

* Fixes mostrecent.fields in config. (closes #133 )
Signed-off-by: PaulinaLach paulina.malgorzata.lach@cern.ch

global: ``mostrecent.fields`` name change

---

invenio_records_rest/links.py
tests/test_links.py

* Adds the capability to specify additional links for a record. (closes #46)
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

links: additional links

---

CHANGES.rst
README.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py
setup.py

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

release v1.0.0b1

---

CHANGES.rst
RELEASE-NOTES.rst
invenio_records_rest/version.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>

release: v1.0.0b3

---

.editorconfig
.gitignore
.travis.yml
CONTRIBUTING.rst
INSTALL.rst
MANIFEST.in
README.rst
RELEASE-NOTES.rst
docs/Makefile
docs/authors.rst
docs/changes.rst
docs/conf.py
docs/contributing.rst
docs/examplesapp.rst
docs/index.rst
docs/installation.rst
docs/make.bat
examples/app-setup.sh
examples/app-teardown.sh
examples/app.py
invenio_records_rest/config.py
invenio_records_rest/errors.py
pytest.ini
requirements-devel.txt
run-tests.sh
setup.cfg
setup.py
tests/conftest.py
tests/mappings/__init__.py
tests/test_examples_app.py

* Updated module and general file structure according to latest
cookiecutter-invenio-module.
(closes #159)
* Updated copyright to 2017 where applicable
* Fixed typos
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

global: release-checklist

---

docs/api.rst
docs/conf.py
docs/configuration.rst
invenio_records_rest/errors.py
invenio_records_rest/ext.py
invenio_records_rest/facets.py
invenio_records_rest/links.py
invenio_records_rest/sorter.py
invenio_records_rest/utils.py
invenio_records_rest/views.py
pytest.ini

Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

docs: restructuring API docs

---

invenio_records_rest/query.py
setup.py

* Removes invenio-query-parser as a dependence. (addresses #190)

installation: invenio-query-parser removal

---

invenio_records_rest/__init__.py

[ci skip]
(Closes https://github.com/inveniosoftware/invenio-records-rest/issues/164, https://github.com/inveniosoftware/invenio-records-rest/issues/180)
Signed-off-by: Diego Rodriguez Rodriguez <diego.rodriguez.rodriguez@cern.ch>
Co-Authored-By: Dinos Kousidis <konstantinos.kousidis@cern.ch>

docs: usage

---

.travis.yml
examples/data/v6/__init__.py
examples/data/v6/testrecords/testrecord-v1.0.0.json
invenio_records_rest/views.py
setup.py
tests/conftest.py
tests/mock_module/mappings/v6/__init__.py
tests/mock_module/mappings/v6/invenio-records-rest/testrecord.json

global: elasticsearch v6 support

---

invenio_records_rest/serializers/fields/__init__.py
invenio_records_rest/serializers/fields/datetime.py
invenio_records_rest/serializers/fields/sanitizedhtml.py
invenio_records_rest/serializers/fields/sanitizedunicode.py
invenio_records_rest/serializers/fields/trimmedstring.py
invenio_records_rest/serializers/schemas/json.py
setup.py
tests/test_custom_fields.py

Addresses https://github.com/inveniosoftware/cookiecutter-invenio-datamodel/issues/4
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

serializers: addition of generic fields

---

examples/app.py
invenio_records_rest/ext.py
invenio_records_rest/views.py
setup.py
tests/conftest.py

* Introduces an "invenio_base.api_blueprints" to load REST API
blueprints via a function. (closes #209)

global: load blueprints from entrypoint

---

examples/app.py
invenio_records_rest/ext.py
invenio_records_rest/serializers/loaders/__init__.py
invenio_records_rest/serializers/loaders/marshmallow.py
invenio_records_rest/serializers/marshmallow.py
invenio_records_rest/views.py
setup.py
tests/conftest.py
tests/test_marshmallow_loader.py

serializers: PID in marshmallow context

---

invenio_records_rest/schemas/fields/__init__.py
invenio_records_rest/schemas/fields/persistentidentifier.py
tests/data/testrecords.json
tests/test_marshmallow_loader.py
tests/test_serializer_json.py

Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

schemas: addition of PersistentIdentifier field

---

CHANGES.rst
invenio_records_rest/schemas/fields/persistentidentifier.py
invenio_records_rest/schemas/json.py
invenio_records_rest/version.py

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

release: v1.2.0

---

invenio_records_rest/facets.py
tests/test_facets.py

Fixes utf in types for ES filter.

facets: change `str` to `text_type`

---

CHANGES.rst
invenio_records_rest/version.py

Signed-off-by: Harris Tzovanakis <me@drjova.com>

release: v1.2.2

---

invenio_records_rest/__init__.py

docs: query parsing example code

---

invenio_records_rest/config.py
invenio_records_rest/views.py

There were no references to `resolver` in `invenio-deposit` or in any other repo in `org:inveniosoftware`.

Fix unused record_class parameter

---

.travis.yml
setup.py

Fix for travis build
* pin pytest, upgrade sphinx, pin dist to trusty, remove ES2

global: fix travis build

---

.travis.yml
invenio_records_rest/views.py
setup.py

The error matches with the title of #243 `local variable 'pid' referenced before assignment` but the description of that issue seems to be for something different so I didn't add the closes ...
Also, I made the PR on `main-1.2` because https://invenio.readthedocs.io/en/latest/releases/maintenance-policy.html#policy
> A minor release A.B (e.g. v3.0) is supported with bug and security fixes (via patch releases) until the release of A.B+2 (e.g. v3.2) and minimum one year.
Let me know if you want to change this.

views: small fix on pass_record raise block

---

setup.py

installation: add "elasticsearch2" extra

---

.travis.yml
docs/conf.py
invenio_records_rest/errors.py
invenio_records_rest/facets.py
invenio_records_rest/utils.py
invenio_records_rest/views.py
setup.py
tests/test_facets.py
tests/test_views_search.py

Added support for from_record parameter.
Added support for facets parameter which allows to turn on specified
facets or to turn off all of them.
closes #258
closes #261

views: Add support for elements required for infinite scroll.

---

examples/app.py
examples/requirements.txt
invenio_records_rest/schemas/fields/sanitizedhtml.py
setup.py
tests/conftest.py

config: Use html sanitizing tags and attrs from config

---

CHANGES.rst
invenio_records_rest/version.py
setup.py

release: 1.5.0

---

CHANGES.rst
invenio_records_rest/version.py
setup.py

* fix version conflicts in (invenio-records-files)

global: bump six version

---

CHANGES.rst
setup.py

global: fix for classifiers

---

CHANGES.rst
invenio_records_rest/version.py

Need to check if #291 should be merged first?
Also, we're missing Github Actions

release: v1.8.0

---

CHANGES.rst
invenio_records_rest/__init__.py

Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …

release: v2.3.1

---

setup.cfg

See https://github.com/inveniosoftware/invenio-i18n/issues/103

 i18n-global: add compile-catalog fuzzy

---

CHANGES.rst
invenio_records_rest/__init__.py

* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …

release: v2.4.1

---

.github/workflows/pypi-publish.yml
.github/workflows/tests.yml
CHANGES.rst
invenio_records_rest/__init__.py
setup.cfg
tests/conftest.py
tests/test_custom_endpoints.py

- setup: bump major dependencies
- setup: change to reusable workflows
- release: v3.0.0

bump major

---

.github/workflows/tests.yml
invenio_records_rest/config.py
invenio_records_rest/errors.py
invenio_records_rest/views.py
run-tests.sh
tests/conftest.py

I18n: Mark Missing Translations Backport

---

.github/workflows/i18n-pull.yml
.github/workflows/i18n-push.yml

i18n: add workflows for pulling and pushing translations

---

.tx/config
setup.cfg

I18n-fix-transifex-pull-error

---

.gitignore
.tx/config
invenio_records_rest/translations/messages.pot
setup.cfg

I18n: forward port transifex changes

---

.github/workflows/pypi-publish.yml
CHANGES.rst
invenio_records_rest/__init__.py

Release v2.5.0

---

invenio_records_rest/serializers/datacite.py
tests/test_serializer_datacite.py

- fix: remove datacite schema31 support
- feat: add schema support up to 45

fix errors
